name: Build MudletBootstrap
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    name: ${{matrix.buildname}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            buildname: 'Linux'
            triplet: x64-linux
            compiler: clang_64
            qt: '6.8.1'
          - os: macos-13
            buildname: 'macOS'
            triplet: x64-osx
            compiler: clang_64
            qt: '6.8.1'
          - os: windows-2025
            buildname: 'Windows'
            qt: '6.8.1'

    steps:

    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Install Qt
      if: runner.os == 'Linux' || runner.os == 'macOS'
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{matrix.qt}}
        dir: ${{runner.workspace}}
        cache: true

    - name: Use CMake 3.30.3
      if: runner.os == 'Linux' || runner.os == 'macOS'
      uses: lukka/get-cmake@v3.30.3

    - name: (macOS) Install dependencies
      if: runner.os == 'macOS'
      env:
        HOMEBREW_NO_ANALYTICS: "ON"
        HOMEBREW_NO_AUTO_UPDATE: "ON"
        HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
        HOMEBREW_NO_INSTALL_CLEANUP: "ON"
        QT_VERSION: ${{ matrix.qt }}
      run: |
        # dependencies needed for vcpkg specifically.
        BREWS=("automake" "autoconf" "pkg-config" "ccache")

        # Loop through each brew package
        for brew in "${BREWS[@]}"; do
         if ! brew list --formula "${brew}" &>/dev/null; then
          echo "Installing ${brew}..."
          brew install "$brew"
         else
          echo "${brew} is already installed."
         fi
        done

        # Set these here so that vcpkg can use them.
        # Use latest available XCode
        echo "DEVELOPER_DIR=$(xcode-select --print-path)" >> $GITHUB_ENV
        echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV
        echo "CCACHE_DIR=${{runner.workspace}}/ccache" >> $GITHUB_ENV

    - name: (Linux) Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install ccache pkg-config

        echo "CCACHE_DIR=${{runner.workspace}}/ccache" >> $GITHUB_ENV

    - name: (Windows) Setup MSYS2
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
    
    - name: (Windows) Build Environment Setup
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        $GITHUB_WORKSPACE/CI/setup-win-sdk.sh
      #  echo "QT_ROOT=${{runner.workspace}}/qt-static-install" >> $GITHUB_ENV

    #- name: (Windows) Restore Qt cache
    #  if: runner.os == 'Windows'
    #  id: restore-qt
    #  uses: actions/cache/restore@v4
    #  with:
    #    path: ${{env.QT_ROOT}}
    #    key: qt

    #- name: (Windows) Compile Qt
    #  if: runner.os == 'Windows' && steps.restore-qt.outputs.cache-hit != 'true'
    #  shell: msys2 {0}
    #  run: $GITHUB_WORKSPACE/CI/compile-qt-win.sh

    #- name: (Windows) Save Qt cache
    #  if: runner.os == 'Windows' && steps.restore-qt.outputs.cache-hit != 'true'
    #  uses: actions/cache/save@v4
    #  with:
    #    path: ${{env.QT_ROOT}}
    #    key: ${{ steps.restore-qt.outputs.cache-primary-key }}

    - name: Restore ccache
      id: restore-ccache
      uses: actions/cache/restore@v4
      with:
        path: ${{runner.workspace}}/ccache
        key: ccache-${{matrix.os}}-${{matrix.buildname}}-${{ github.sha }}
        restore-keys: ccache-${{matrix.os}}-${{matrix.buildname}}

    - name: check ccache stats prior to build
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: ccache --zero-stats --show-stats

    - name: (Linux, macOS) Build
      if: runner.os == 'Linux' || runner.os == 'macOS'
      env:
        CMAKE_PREFIX_PATH: ${{ env.QT_PREFIX != '' && env.QT_PREFIX || env.MINGW_BASE_DIR }}
      run: |
        chmod +x $GITHUB_WORKSPACE/CI/build.sh
        $GITHUB_WORKSPACE/CI/build.sh

    - name: (Windows) Build
      if: runner.os == 'Windows'
      env:
        CMAKE_PREFIX_PATH: ${{ env.QT_PREFIX != '' && env.QT_PREFIX || env.MINGW_BASE_DIR }}
      shell: msys2 {0}
      run: |
        # Clean up unnecessary plugin cmake files to avoid CMake errors
        echo "Cleaning up unused Qt plugin .cmake files..."
        find "$CMAKE_PREFIX_PATH/lib/cmake/Qt6" -iname '*plugin*.cmake' -delete

        echo "Cleaning up known problematic dependencies..."
        find "$CMAKE_PREFIX_PATH/lib/cmake/Qt6"* -iname '*Dependencies.cmake' \
          -exec grep -q -E "BundledOpenXR|3DLogic|Vulkan|TIFF|Jpeg|VirtualKeyboard" {} \; \
          -exec rm -f {} +
          
        chmod +x $GITHUB_WORKSPACE/CI/build.sh
        $GITHUB_WORKSPACE/CI/build.sh

    #- name: (Windows) Build
    #  if: runner.os == 'Windows'
    #  shell: msys2 {0}
    #  run: $GITHUB_WORKSPACE/CI/build-win.sh

    - name: Save ccache
      if: always() && steps.restore-ccache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{runner.workspace}}/ccache
        key: ${{ steps.restore-ccache.outputs.cache-primary-key }}

    - name: check ccache stats post build
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: ccache --show-stats

    - name: (Windows) Package
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: $GITHUB_WORKSPACE/CI/package-win.sh

    - name: (Windows) Deploy
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: $GITHUB_WORKSPACE/CI/deploy-win.sh

    - name: (macOS) Prep for Artifact Upload
      if: runner.os == 'macOS'
      env:
        BUILD_DIR: ${{runner.workspace}}/build
      run: |
        chmod +x $GITHUB_WORKSPACE/CI/package-mac.sh
        $GITHUB_WORKSPACE/CI/package-mac.sh

    - name: (Linux) Prep for Artifact Upload
      if: runner.os == 'Linux'
      env:
        BUILD_DIR: ${{runner.workspace}}/build
      run: |
        chmod +x $GITHUB_WORKSPACE/CI/package-linux.sh
        $GITHUB_WORKSPACE/CI/package-linux.sh

    - name: Upload Packaged Product
      uses: actions/upload-artifact@v4
      if: env.UPLOAD_FILENAME
      with:
        name: ${{env.UPLOAD_FILENAME}}
        path: ${{env.FOLDER_TO_UPLOAD}}

